# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="lambda"

plugins=(
    git
    dnf
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Keybindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region

# check the dnf plugins commands here
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/dnf

# Set-up FZF key bindings (CTRL R for fuzzy history finder)
source <(fzf --zsh)
eval "$(zoxide init zsh)"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# golang
export PATH=$PATH:/usr/local/go/bin

# Freetype font rendering tweaks
export FREETYPE_PROPERTIES="truetype:interpreter-version=35 autofitter:no-stem-darkening=0 cff:no-stem-darkining=0"

zstyle ':completion:*' file-sort date
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:paths' path-completion yes
zstyle ':completion:*:processes' command 'ps -afu $USER'
zstyle ':autocomplete:*' min-input 1
zstyle ':autocomplete:*' insert-unambiguous yes

export EDITOR=nvim

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

setopt CORRECT

# Open buffer line in editor
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

bindkey '^z' undo

# Set-up icons for files/directories in terminal using lsd
alias cl='clear'
alias v='nvim'
alias op='opencode'
alias ls='eza --icons --color=always --group-directories-first'
alias l='eza -F --icons --color=always --group-directories-first'
alias la='eza -la --icons --color=always --group-directories-first'
alias ll='eza -alF --icons --color=always --group-directories-first'
alias lt='eza --tree --icons --color=always --group-directories-first'
alias lf='yazi'
alias ..='cd ..'
alias ga='git add .'
alias gs='git status'
alias gc='git commit -m'
alias ff='fastfetch'
alias ffc='fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc'
alias tl='tmux list-sessions'
alias ta='tmux attach'
alias tn='tmux new-session'
alias ts='tmux source-file ~/.config/tmux/.tmux.conf'
alias uu='sudo dnf update && sudo dnf upgrade && flatpak update'
alias i='sudo dnf install'
alias r='sudo dnf remove'
alias s='sudo dnf search'
alias cat='bat -p'
alias wm='wifimenu'
alias pm='powermenu'
alias ned='ln -s ../../node_modules node_modules && ln -s ../../.env.local .env.local & ln -s ../../.dev.vars .dev.vars'

# opencode
export PATH=$HOME/.opencode/bin:$PATH
